# Numpy

NumPy, short for Numerical Python, is the fundamental package required for high performance scientific computing and data analysis.

While NumPy by itself does not provide very much high-level data analytical func- tionality, having an understanding of NumPy arrays and array-oriented computing will help you use tools like pandas much more effectively. 

In [2]:
import numpy

In [ ]:
dir(numpy)

In [ ]:
help(numpy.zeros)

In [5]:
a = numpy.zeros( (3,5) )        

In [6]:
a

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [8]:
a[(2,2)] = 3
a

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  3.,  0.,  0.]])

In [10]:
import numpy as np

### 1-D array

In [12]:
b = np.array( [2., 4., 6.])
b

array([ 2.,  4.,  6.])

In [14]:
b = np.array( range(10) )
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
b = np.array( (2., 4., 6.) )
b            

array([ 2.,  4.,  6.])

### 2-D array (matrix)

In [16]:
m = np.array( [(2., 3., 4.), (5., 6., 7.)])
m

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.]])

In [18]:
m = np.array( [[2., 3., 4.], [5., 6., 7.]] )
m

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.]])

In [21]:
m * 3

array([[  6.,   9.,  12.],
       [ 15.,  18.,  21.]])

In [20]:
m + m

array([[  4.,   6.,   8.],
       [ 10.,  12.,  14.]])